language: go
addons:
  apt:
    sources:
      - augeas
    packages:
      - libaugeas-dev
go:
- 1.6
after_success:
- go get github.com/mattn/goveralls
- "$HOME/gopath/bin/goveralls -service=travis-ci"
